
import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { Metadata } from "next";
import { Toaster } from "sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Cario - AI Career Coach",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{
      baseTheme: "dark",
      }}>
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          {/* header */}
          <Header />
          {/* main content */}
          <main className="min-h-screen">
          {children}
          </main>
          <Toaster richColors/>
          {/* footer */}
          <footer className="bg-muted/50 py-12">
          <Footer className="container" />
          </footer>
        </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
